import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const minecraftFont = localFont({
  src: "./fonts/minecraft_font.woff",
  variable: "--font-minecraft_font",
  // weight: "100 900",
});
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${minecraftFont.variable}  antialiased`}>
        {children}
      </body>
    </html>
  );
}
